#! /usr/bin/env python3
import os

makefile = '''CC = clang
CFLAGS = -Wall -Wextra

all: part1 part2

part1: src/part1.o
	$(CC) $(CFLAGS) -L../lib -o part1 $^ -laoc

part2: src/part2.o
	$(CC) $(CFLAGS) -L../lib -o part2 $^ -laoc

src/%.o: src/%.c
	$(CC) $(CFLAGS) -I../include -c -o $@ $^

.PHONY: clean
clean:
	-rm -rf src/*.o
'''

def createMakefile():
    with open('Makefile', 'w') as fd:
        fd.write(makefile)

def partStr(num):
    return '''
#include <aoc.h>
#include <stdio.h>

int main(void) {{
    printf("Hello, Part{}!\\n");

    return 0;
}}
    '''.format(num)

def createPart(num):
    name = f'part{num}.c'
    with open(name, 'w') as part:
        part.write(partStr(num))

def main():
    print('Setting up AOC format...')

    createMakefile()
    print('Created Makefile')

    os.mkdir('src')
    os.chdir('src')
    print('Created src directory')

    createPart('1')
    print('Created part1.c')

    createPart('2')
    print('Created part2.c')

if __name__ == '__main__':
  main()
